import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.normal] 
family = "Hack Nerd Font"
style = "Regular"

[window]
decorations = "Transparent"
padding = { x = 0, y = 25 }
